id: PD6721660
initial_creation_type: input
source_metadata:
  title: Śāntideva Series
  language: bo
  description: 'Texts by and about the Indian master Śāntideva (zhi ba lha), renowned
    author of the Bodhicaryāvatāra:'
  volume:
    4b5386b88bae4b558a0d07ed48b3de64:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    6986897c9ee0475a932c2a1369a7f8bd:
      title: 'Bodhicaryāvatāra—Chapter 1: The Benefits of Bodhicitta'
      parent: Bodhicaryāvatāra Root Text
    ce240638c8e9421a86f4d9627b6a0a00:
      title: 'Bodhicaryāvatāra—Chapter 2: Confession of Negativity'
      parent: Bodhicaryāvatāra Root Text
    e8048acfefd147cdad224329ce030b02:
      title: 'Bodhicaryāvatāra—Chapter 3: Fully Adopting Bodhicitta'
      parent: Bodhicaryāvatāra Root Text
    dea6672694484fb38d05249ec6357b72:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
created_at: '2022-03-01T02:22:42.796529'
last_modified_at: '2022-03-01T02:22:42.796532'
statistics:
  total_words: 8285
  total_non_words: 805
quality:
  non_words_ratio: 0.1
